import React, { useEffect, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import HomeTiles from "../components/homeTiles";
// import { Web3Auth } from "@web3auth/web3auth";
// import {
//   CHAIN_NAMESPACES,
//   SafeEventEmitterProvider,
//   WALLET_ADAPTERS,
// } from "@web3auth/base";
// import { Web3AuthCore } from "@web3auth/core";
// import { OpenloginAdapter } from "@web3auth/openlogin-adapter";
// // import RPC from "../services/web3RPC"; // for using web3.js
// // import { Web3AuthProvider } from "../services/web3auth";
// // import { useWeb3Auth } from "../services/web3auth";

import { CHAIN_CONFIG_TYPE } from "../config/chainConfig";
import { WEB3AUTH_NETWORK_TYPE } from "../config/web3AuthNetwork";
import { Web3AuthProvider } from "../services/web3auth";
import Setting from "../components/setting";
import Main from "../components/main";

const Home: NextPage = () => {
  const [web3AuthNetwork, setWeb3AuthNetwork] =
    useState<WEB3AUTH_NETWORK_TYPE>("mainnet");
  const [chain, setChain] = useState<CHAIN_CONFIG_TYPE>("mainnet");

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div className="grid">{provider ? loggedInView : unloggedInView}</div> */}
      <main className={styles.main}>
        <div className={styles.container}>
          <Web3AuthProvider chain={chain} web3AuthNetwork={web3AuthNetwork}>
            {/* <h1 className={styles.title}>
              <a
                target="_blank"
                href="http://web3auth.io/"
                rel="noreferrer noopener"
              >
                Web3Auth
              </a>{" "}
              & NextJS Example
            </h1>
            <Setting setNetwork={setWeb3AuthNetwork} setChain={setChain} /> */}
            <Main />
          </Web3AuthProvider>
        </div>
        
        <h1>Portal</h1>
        <HomeTiles />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
